test: testphysx.cpp
	clang++ -I/home/will/projects/cpprtx/libs/physx/physx/include -I/home/will/projects/cpprtx/libs/physx/physx/snippets -L/home/will/projects/cpprtx/libs/physx/physx/bin/linux.clang/release testphysx.cpp -o test
